
/*------------------------------------------------------------------------
    File        : ILogging
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Sun Nov 08 12:09:44 CET 2015
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface bfv.spring4oe.sample.ILogging:  
  
  method public void Log(messageText as character).
  
end interface.